export { default as Footer } from './Footer';
export { default as Layout } from './Layout';
export { default as Navbar } from './Navbar';
export { default as Product } from './Product';
export { default as ApplePhone } from './ApplePhone';
export { default as SamsungPhone } from './SamsungPhone';
export { default as HeroBanner } from './HeroBanner';
export { default as FooterBanner } from './FooterBanner';
export { default as Cart } from './Cart';